# -*- coding: utf-8 -*-
"""cancer_paitent_model_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGdP03kNeS4v0DDMaw6XOUKhentikPqw
"""

import streamlit as st
import numpy as np
import joblib

# Load trained model
model = joblib.load("cancer_patient_acc_lr_model.pkl")

st.title("Cancer Risk Prediction System")

st.write("Enter patient details")

age = st.number_input("Age")
air_pollution = st.number_input("Air Pollution")
smoking = st.number_input("Smoking")
alcohol = st.number_input("Alcohol Use")
genetic_risk = st.number_input("Genetic Risk")
obesity = st.number_input("Obesity")
chest_pain = st.number_input("Chest Pain")

features = np.array([[age,air_pollution,smoking,alcohol,genetic_risk,obesity,chest_pain]])

if st.button("Predict Cancer Risk"):

    prediction = model.predict(features)

    if prediction == 0:
        st.success("Low Cancer Risk")
    elif prediction == 1:
        st.warning("Medium Cancer Risk")
    else:
        st.error("High Cancer Risk")
